import { useState } from 'react';
import { Card } from "@heroui/react";
import { GeneratedFile } from '../types';

interface CodebaseViewerProps {
    files?: GeneratedFile[];
}

export const CodebaseViewer = ({ files = [] }: CodebaseViewerProps) => {
    const [activeFile, setActiveFile] = useState<string>(files.length > 0 ? files[0].name : '');

    if (!files || files.length === 0) {
        return (
            <Card className="h-full flex items-center justify-center p-8 bg-zinc-50 dark:bg-zinc-900 border-dashed border-2 border-zinc-200 dark:border-zinc-800">
                <div className="text-center text-default-400">
                    <p className="text-xl mb-2">📄</p>
                    <p>No code generated yet</p>
                </div>
            </Card>
        );
    }

    const currentFile = files.find(f => f.name === activeFile) || files[0];

    return (
        <Card className="h-full flex flex-col overflow-hidden bg-[#1e1e1e] border-zinc-800">
            {/* Tabs / Sidebar */}
            <div className="flex border-b border-zinc-800 overflow-x-auto bg-[#252526]">
                {files.map(file => (
                    <button
                        key={file.name}
                        onClick={() => setActiveFile(file.name)}
                        className={`px-4 py-2 text-sm font-mono border-r border-zinc-800 hover:bg-[#2a2d2e] transition-colors whitespace-nowrap
                            ${activeFile === file.name ? 'bg-[#1e1e1e] text-white border-t-2 border-t-blue-500' : 'text-zinc-400'}`}
                    >
                        {file.name}
                    </button>
                ))}
            </div>

            {/* Code Content */}
            <div className="flex-1 overflow-auto p-4 font-mono text-sm">
                <pre className="text-zinc-300">
                    <code>{currentFile.code}</code>
                </pre>
            </div>

            {/* Footer / Status */}
            <div className="px-4 py-1 bg-blue-600 text-white text-xs font-mono flex justify-between">
                <span>{currentFile.language}</span>
                <span>Generated by Deep Research</span>
            </div>
        </Card>
    );
};
